CREATE DATABASE tickets OWNER program;
GRANT ALL PRIVILEGES ON DATABASE tickets TO program;

CREATE DATABASE flights OWNER program;
GRANT ALL PRIVILEGES ON DATABASE flights TO program;

CREATE DATABASE privileges OWNER program;
GRANT ALL PRIVILEGES ON DATABASE privileges TO program;
